### ISSUE TITLE
[Bug] Password field is shown as plain text

### ISSUE THREAD

**Issue by olivierobert** [pongdanaiNil/code-challenge-frontend#2]
## Issue

The password text field is incorrectly defined as it shows the password content:

![image](https://user-images.githubusercontent.com/696529/222374542-591db9ad-5721-45f9-8ab6-76bff96151ed.png)

## Expected

Both password and password confirmation field must obfuscate the typed content for security purposes.

> **Note**
> While minor, this kind of bugs demonstrates the benefits of having unit tests for components.

**Comment by pongdanaiNil** [comment]
I have fixed the bug in the password field to obfuscate the typed content.
You can check out [this merged pull request.](https://github.com/pongdanaiNil/code-challenge-frontend/pull/5)

From my experience, my previous company always used Cypress for UI testing, and there will be QAs who write testing scripts. So I am not familiar with the UI testing tool.

If there are any questions or suggestions, please let me know.

**Comment by olivierobert** [comment]
Understood of your limited experience in that area. It helps to better gauge your skills so thank you for openly sharing this.
